### ISSUE TITLE
Target folder name is optional for the `init` command

### ISSUE THREAD

**Issue by HenrikHarmer** [krisquigley/caerus#11]
When running the command `node dist/lib/cli/cli.js init`, users do not have to provide a target project/folder name. As a result, the `argv.name` property is always `undefined`, resulting in the output being placed into a folder called `undefined`.

Two options spring to mind: change `initialize.ts` so the `command` uses a required argument:

`
export const command = 'init <name>;
`

Alternatively, check if `argv.name` is `undefined` - if it is, use a default folder name, otherwise accept the input provided by the user.

**Comment by krisquigley** [comment]
I would say we need to make the argument required as the name is used for setting a lot if information within the initialize command.

**Comment by HenrikHarmer** [comment]
Happy to send you a pull request if you can grant me access to the project as a collaborator.
